import "~/styles/globals.css";
import "dayjs/locale/cs";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import { DatesProvider } from "@mantine/dates";
import { Notifications } from "@mantine/notifications";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { TRPCReactProvider } from "~/trpc/react";

import { ThemeProvider } from "./theme-provider";

export const metadata: Metadata = {
  title: "Výkazy a faktury",
  description: "Správa výkazů práce a fakturace",
  // Favicon/apple touch icon are generated by Next.js itself from src/app/icon.tsx and
  // src/app/apple-icon.tsx (file convention), no manual "icons" field needed.
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="cs" className={geist.variable} {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body>
        <NuqsAdapter>
          <ThemeProvider>
            <DatesProvider settings={{ locale: "cs" }}>
              <Notifications position="top-right" />
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </DatesProvider>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
