import { NextResponse } from "next/server";

import { uncachedAuth } from "~/server/auth";

// Favicon/OG images (src/app/icon.tsx etc.) are generated by Next as a route with no
// file extension in the URL (unlike favicon.ico) — the matcher below therefore doesn't
// exclude them, and without this the proxy would redirect them to /login. That would
// break not just the favicon in an unauthenticated visitor's tab, but especially link
// previews on Slack/Twitter/etc. — those requests never authenticate, so they'd get a
// redirect to /login instead of the image.
const PUBLIC_PATHS = ["/login", "/icon", "/apple-icon", "/opengraph-image", "/twitter-image"];

export default uncachedAuth((req) => {
  const isPublic =
    PUBLIC_PATHS.some((p) => req.nextUrl.pathname.startsWith(p)) ||
    req.nextUrl.pathname.startsWith("/api/auth");

  if (!req.auth && !isPublic) {
    const loginUrl = new URL("/login", req.nextUrl.origin);
    loginUrl.searchParams.set("callbackUrl", req.nextUrl.pathname);
    return NextResponse.redirect(loginUrl);
  }

  if (req.auth && req.nextUrl.pathname === "/login") {
    return NextResponse.redirect(new URL("/", req.nextUrl.origin));
  }

  return NextResponse.next();
});

export const config = {
  // Skip static assets, images, and Next.js internal paths.
  matcher: ["/((?!_next/static|_next/image|favicon.ico|.*\\.(?:png|svg|jpg|jpeg|gif|webp)$).*)"],
};
